"""add_profile_fields

Revision ID: 02e8ddbe44b0
Revises: 1820d650ee55
Create Date: 2026-07-14 15:31:00.927062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e8ddbe44b0'
down_revision: Union[str, Sequence[str], None] = '1820d650ee55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_profiles', sa.Column('service_type', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('unit_name', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('food_preferences_allergies', sa.String(), nullable=True))
    op.add_column('guest_profiles', sa.Column('release_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guest_profiles', sa.Column('origin_city', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('full_address', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('max_guests', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('host_profiles', sa.Column('num_bedrooms', sa.Integer(), nullable=True))
    op.add_column('host_profiles', sa.Column('has_pets', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('host_profiles', sa.Column('accessibility', sa.String(), nullable=True))
    op.add_column('host_profiles', sa.Column('free_text_notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('biography', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biography')
    op.drop_column('host_profiles', 'free_text_notes')
    op.drop_column('host_profiles', 'accessibility')
    op.drop_column('host_profiles', 'has_pets')
    op.drop_column('host_profiles', 'num_bedrooms')
    op.drop_column('host_profiles', 'max_guests')
    op.drop_column('host_profiles', 'full_address')
    op.drop_column('guest_profiles', 'origin_city')
    op.drop_column('guest_profiles', 'release_date')
    op.drop_column('guest_profiles', 'food_preferences_allergies')
    op.drop_column('guest_profiles', 'unit_name')
    op.drop_column('guest_profiles', 'service_type')
    # ### end Alembic commands ###
