"""add is_direct_request to guest_posts

Revision ID: 04af2f426d6b
Revises: e97f0f5eddfc
Create Date: 2026-07-23 18:42:30.520911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04af2f426d6b'
down_revision: Union[str, Sequence[str], None] = 'e97f0f5eddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_host_guest_blocks_guest_profile_id'), table_name='host_guest_blocks')
    op.drop_index(op.f('ix_host_guest_blocks_host_profile_id'), table_name='host_guest_blocks')
    op.drop_table('host_guest_blocks')
    op.add_column('guest_posts', sa.Column('is_direct_request', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_posts', 'is_direct_request')
    op.create_table('host_guest_blocks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('host_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('guest_profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['guest_profile_id'], ['guest_profiles.id'], name=op.f('host_guest_blocks_guest_profile_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profiles.id'], name=op.f('host_guest_blocks_host_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('host_guest_blocks_pkey'))
    )
    op.create_index(op.f('ix_host_guest_blocks_host_profile_id'), 'host_guest_blocks', ['host_profile_id'], unique=False)
    op.create_index(op.f('ix_host_guest_blocks_guest_profile_id'), 'host_guest_blocks', ['guest_profile_id'], unique=False)
    # ### end Alembic commands ###
