"""Initial migrations

Revision ID: 1820d650ee55
Revises: 
Create Date: 2026-07-14 12:04:16.359478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '1820d650ee55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('HOST', 'GUEST', 'ADMIN', name='usertype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('guest_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_soldier_or_national_service', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('skills_give_take', sa.String(length=500), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('preference_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_profiles_user_id'), 'guest_profiles', ['user_id'], unique=True)
    op.create_table('host_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('kashrut_level', sa.Enum('NONE', 'BASIC', 'KOSHER', 'GLATT_MEHADRIN', name='kashrutlevel'), nullable=False),
    sa.Column('religious_orientation', sa.String(length=100), nullable=True),
    sa.Column('availability_windows', sa.String(length=255), nullable=True),
    sa.Column('atmosphere_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_profiles_city'), 'host_profiles', ['city'], unique=False)
    op.create_index(op.f('ix_host_profiles_user_id'), 'host_profiles', ['user_id'], unique=True)
    op.create_table('guest_posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('guest_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'MATCHED', name='poststatus'), nullable=False),
    sa.Column('requested_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('guests_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('claimed_by_host_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_host_id'], ['host_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_profile_id'], ['guest_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_posts_claimed_by_host_id'), 'guest_posts', ['claimed_by_host_id'], unique=False)
    op.create_index(op.f('ix_guest_posts_guest_profile_id'), 'guest_posts', ['guest_profile_id'], unique=False)
    op.create_table('host_listings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('max_guests', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_listings_host_profile_id'), 'host_listings', ['host_profile_id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('guest_post_id', sa.Uuid(), nullable=False),
    sa.Column('host_profile_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'REJECTED', name='matchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guest_post_id'], ['guest_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_guest_post_id'), 'matches', ['guest_post_id'], unique=False)
    op.create_index(op.f('ix_matches_host_profile_id'), 'matches', ['host_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_host_profile_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_guest_post_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_host_listings_host_profile_id'), table_name='host_listings')
    op.drop_table('host_listings')
    op.drop_index(op.f('ix_guest_posts_guest_profile_id'), table_name='guest_posts')
    op.drop_index(op.f('ix_guest_posts_claimed_by_host_id'), table_name='guest_posts')
    op.drop_table('guest_posts')
    op.drop_index(op.f('ix_host_profiles_user_id'), table_name='host_profiles')
    op.drop_index(op.f('ix_host_profiles_city'), table_name='host_profiles')
    op.drop_table('host_profiles')
    op.drop_index(op.f('ix_guest_profiles_user_id'), table_name='guest_profiles')
    op.drop_table('guest_profiles')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
