"""add_host_availability_tables

Revision ID: 19f0819d1d0a
Revises: c10446bb3eca
Create Date: 2026-07-23 00:39:04.086903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19f0819d1d0a'
down_revision: Union[str, Sequence[str], None] = 'c10446bb3eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_availability_overrides',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_profile_id', sa.Uuid(), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='overridestatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_profile_id', 'override_date', name='uq_host_override_date')
    )
    op.create_index(op.f('ix_host_availability_overrides_host_profile_id'), 'host_availability_overrides', ['host_profile_id'], unique=False)
    op.create_index(op.f('ix_host_availability_overrides_override_date'), 'host_availability_overrides', ['override_date'], unique=False)
    op.create_table('host_availability_rules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('host_profile_id', sa.Uuid(), nullable=False),
    sa.Column('weekend_pattern', sa.String(), server_default=sa.text("'every'"), nullable=False),
    sa.Column('biweekly_parity', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('monthly_occurrence', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('weekend_days', sa.String(), server_default=sa.text("'5,6'"), nullable=False),
    sa.Column('weekday_open_days', sa.String(), server_default=sa.text("''"), nullable=False),
    sa.Column('notice_cutoff_hour', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_profile_id'], ['host_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_availability_rules_host_profile_id'), 'host_availability_rules', ['host_profile_id'], unique=True)
    op.alter_column('host_profiles', 'available_spots',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('host_profiles', 'has_lodging',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('host_profiles', 'has_lodging',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('host_profiles', 'available_spots',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.drop_index(op.f('ix_host_availability_rules_host_profile_id'), table_name='host_availability_rules')
    op.drop_table('host_availability_rules')
    op.drop_index(op.f('ix_host_availability_overrides_override_date'), table_name='host_availability_overrides')
    op.drop_index(op.f('ix_host_availability_overrides_host_profile_id'), table_name='host_availability_overrides')
    op.drop_table('host_availability_overrides')
    # ### end Alembic commands ###
