"""add_date_range_to_guest_posts

Revision ID: 40a52a63125f
Revises: 19f0819d1d0a
Create Date: 2026-07-23 12:39:31.627850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a52a63125f'
down_revision: Union[str, Sequence[str], None] = '19f0819d1d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_posts', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guest_posts', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guest_posts', sa.Column('nights_count', sa.Integer(), server_default=sa.text('1'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_posts', 'nights_count')
    op.drop_column('guest_posts', 'end_date')
    op.drop_column('guest_posts', 'start_date')
    # ### end Alembic commands ###
