"""add_is_anonymous_to_guest_posts

Revision ID: e7b4315a78f6
Revises: 40a52a63125f
Create Date: 2026-07-23 13:02:24.192133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7b4315a78f6'
down_revision: Union[str, Sequence[str], None] = '40a52a63125f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guest_posts', sa.Column('is_anonymous', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guest_posts', 'is_anonymous')
    # ### end Alembic commands ###
