"""Add HostGuestBlock table and rejection_reason

Revision ID: e97f0f5eddfc
Revises: e7b4315a78f6
Create Date: 2026-07-23 16:26:20.997387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97f0f5eddfc'
down_revision: Union[str, Sequence[str], None] = 'e7b4315a78f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
