"""add_verification_fields

Revision ID: ef23f8a2ca54
Revises: 02e8ddbe44b0
Create Date: 2026-07-15 17:38:01.861139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef23f8a2ca54'
down_revision: Union[str, Sequence[str], None] = '02e8ddbe44b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('email_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('is_phone_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('telegram_verification_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_verification_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'telegram_verification_expires_at')
    op.drop_column('users', 'telegram_verification_code')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'email_verification_expires_at')
    op.drop_column('users', 'email_verification_code')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
